events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. CAPA DE CLIENTE: Servir el Frontend de React
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; 
        }

        # 2. PROXY INVERSO: Redirigir la Autenticación a tu servicio de Node.js
        location /api/v1/auth/ {
            proxy_pass http://auth-node:3001/api/v1/auth/;
            
            # 🚀 AQUÍ NACE Y SE PROPAGA EL TRACE_ID PARA NODE:
            proxy_set_header X-Correlation-ID $request_id;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. PROXY INVERSO: Redirigir transacciones y negocio a tu Orquestador de Java
        location /api/v1/orchestrator/ {
            proxy_pass http://orchestrator-java:8080;
            
            proxy_set_header X-Correlation-ID $request_id;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}